name: Unit Tests

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
      - development  # Optionally trigger on other branches

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu environment for running tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment

      # Define Python version (adjust as needed)
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p 'test_*.py'